### ISSUE TITLE
link DOIs to preferred resolver

### ISSUE THREAD

**Issue by katrinleinweber** [isabelle-prover/admin#2]
Hello!

The DOI foundation recommends a [new, secure resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8). Since there some occurrences of `http://dx.doi.org` in the mirrored repos, I thought I notify you of the improvement suggestion to update these to `https://doi.org` here.

Cheers :-)

**Comment by larsrh** [comment]
Hi @katrinleinweber! Indeed, there are a ton of them in the AFP repositories. Thanks for alerting us to this.

**Comment by katrinleinweber** [comment]
You're welcome :-)

**Comment by larsrh** [comment]
Fixed (mostly) in https://bitbucket.org/isa-afp/afp-devel/commits/ff9132bfc1c513697d8efdb3f72f369c99b3f367.
